### ISSUE TITLE
Add Ozone HIS and Madiro logo in the bottom of login page

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#11]
![Image](https://github.com/user-attachments/assets/baac0dc3-047a-44e6-9035-0f649fc6279a)

Example:

![Image](https://github.com/user-attachments/assets/55ce1a9f-581f-4f47-b55d-e5917ca1dd64)

**Comment by suubi-joshua** [comment]
Currently there is no config to help with this. I opened up a ticket in OpenMRS to address this [here](https://openmrs.atlassian.net/browse/O3-3859).

**Comment by michaelbontyes** [comment]
Hi @suubi-joshua , how is it going with this ticket and your investigation within the community? Any chance for the login esm to support more customization? How is Ozone handling this in their demo here https://auth.demo.ozone-his.com/ ? Isn't there any other option than creating a custom login esm? Thanks

**Comment by suubi-joshua** [comment]
Hi @michaelbontyes yes I made some progress here https://github.com/openmrs/openmrs-esm-core/pull/1127 its an open PR. I added configs to allow customization of the logos in the login page just using the configs of the esm login app. The PR is still open.

**Comment by suubi-joshua** [comment]
Hello @michaelbontyes am done with the changes. Every thing works am waiting for a review and a merge https://github.com/openmrs/openmrs-esm-core/pull/1127

**Comment by suubi-joshua** [comment]
Once this PR is merged in core I can then configure the logos in UVL

**Comment by suubi-joshua** [comment]
Some new developments about this issue 
https://openmrs.slack.com/archives/CKS32D55G/p1727938916121129

**Comment by suubi-joshua** [comment]
https://github.com/MadiroGlobalHealth/UVL-EMR/pull/51
PR
