### ISSUE TITLE
Display "Billing" in the sidebar navigation

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#14]
Billing is a feature flag. Is there a way to leverage configs to enable that feature flag by default?

![Image](https://github.com/user-attachments/assets/85939d52-de83-4810-b00f-af3f3366d4ef)

Once enabled, it should show up in the navigation.

**Comment by dancinoman** [comment]
Investigation was made and unfortunately we wont be able to do it. follow this link for further explanation https://openmrs.slack.com/archives/C02UNMKFH8V/p1724886858291809?thread_ts=1724867752.441249&cid=C02UNMKFH8V

**Comment by sherrif10** [comment]
Hello @michaelbontyes , What we can do is to add billing module in the RefApp specifically in our distro as another option. Let me know your suggestion
