### ISSUE TITLE
Create testing users by roles

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#20]
Using a similar method than here with liquibase, create testing users for the different roles:
https://github.com/MSF-OCG/LIME-EMR/blob/main/sites/mosul/configs/openmrs/initializer_config/liquibase/liquibase.xml

Users and roles needed:

| Role                 | Privileges                                                         | Test username | Test password | Is provider? |
|----------------------|--------------------------------------------------------------------|---------------|---------------|--------------|
| Registration Officer | Patient registration (NOT patient summary), View patient queues, Manage appointments | RegistrationOfficer   | Admin123      | No           |
| Nurse  | Same as above + patient summary (create/edit/delete)               | Nurse      | Admin123      | Yes          |
| Doctor  | Same as above + patient summary (create/edit/delete)               | Doctor      | Admin123      | Yes          |
| Lab Technician| Only access to the Lab feature              | LabTechnician     | Admin123      | No          |
| Pharmacist      | Only access to the Pharmacy and dispensing features              | Pharmacist     | Admin123      | No          |
| Cashier | Only access to the Billing feature           | Cashier  | Admin123      | No          |

**Comment by archnalan** [comment]
@sherrif10  Are you still on this? or can i give it a try

**Comment by sherrif10** [comment]
Hello @archnalan, Feel free to give it a try, i will give a look at your changes, Somehow caught up from my ends @michaelbontyes

**Comment by tendomart** [comment]
@archnalan  are you working on this ?
