### ISSUE TITLE
Add missing Lab Tests

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#22]
Compare the list of tests from the UVL requirements:
https://docs.google.com/spreadsheets/d/1ZyqsvdSMR5sJ5JOQN47TLaPucLZOtB5mofWwiooz42E/edit?gid=1036769692#gid=1036769692

And flag the ones already present in the list of Tests in UVL OpenMRS:
http://uvl.southafricanorth.cloudapp.azure.com/openmrs/dictionary/concept.htm?conceptId=1259 

Then add the missing tests in OpenMRS using the "concepts" domain from Initializer. For example to create the concepts:
https://github.com/openmrs/openmrs-distro-referenceapplication/blob/main/distro/configuration/concepts/tests_core-demo.csv
Then add them as members to the concept "Tests Orderability" for them to be visible in the order test dropdown: 
https://github.com/openmrs/openmrs-distro-referenceapplication/blob/main/distro/configuration/concepts/convsets-core_demo.csv

**Comment by Twiineenock** [comment]
Hi @michaelbontyes can I work on this?

**Comment by michaelbontyes** [comment]
Certainly! Thank you

**Comment by tendomart** [comment]
@dancinoman  thought was alone in  this

**Comment by dancinoman** [comment]
![Image](https://github.com/user-attachments/assets/9eb78b27-05c7-4e5a-ba7c-fc3563d144d5)
Does your issue look like this?

**Comment by michaelbontyes** [comment]
@dancinoman this error might occur because you're user is not a provider. You can configure it in the admin, following the explanation [here](https://openmrs.atlassian.net/wiki/spaces/Archives/pages/25521021/Provider+Management+Getting+Started#Adding-New-Providers).

**Comment by dancinoman** [comment]
Yes it worked! Altough I think @tendomart has a different issue @michaelbontyes

**Comment by tendomart** [comment]
> Yes it worked! Altough I think @tendomart has a different issue @michaelbontyes 

Ya right

**Comment by michaelbontyes** [comment]
@tendomart , @dancinoman , do you still have any blockers with this issue? Can you share the video documenting the lab tests available in the system? Thanks

**Comment by tendomart** [comment]
So that's my blocker

**Comment by tendomart** [comment]
@michaelbontyes  the issue i have discovered from  **openmrs-reference-application-3-backend:qa**   , it cannot parse the CSV b
![Screenshot from 2024-10-01 04-40-36](https://github.com/user-attachments/assets/5aa7fef0-aceb-45fa-b274-8b6c015ea91d)
ecause some concepts which I added are missing UUID's and having not been provided from the requirements document, i need to get them from you,incase those concepts already exist.

ERROR

**Comment by michaelbontyes** [comment]
@tendomart did you manage to solve the unterminated quoted field at the end of the CSV? Does it solve your issue?

**Comment by tendomart** [comment]
Yes *michaelbontyes <https://github.com/michaelbontyes> * yes i did remove
the remove it, but without change.

**Comment by michaelbontyes** [comment]
@tendomart I did some tests but no luck yet. I'll dive further tomorrow.

**Comment by tendomart** [comment]
Alright will wait for your feedback as I wait for this as try with single words as members in the convset as well.
