### ISSUE TITLE
Add missing diagnosis

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#23]
Compare the list of diagnosis from the UVL requirements:
https://docs.google.com/spreadsheets/d/1ZyqsvdSMR5sJ5JOQN47TLaPucLZOtB5mofWwiooz42E/edit?gid=46706108#gid=46706108

And flag the ones already present in the list of diagnosis in UVL OpenMRS:
http://uvl.southafricanorth.cloudapp.azure.com/openmrs/dictionary/concept.htm?conceptId=1259

Then add the missing tests in OpenMRS using the "concepts" domain from Initializer. For example to create the concepts:
https://github.com/openmrs/openmrs-distro-referenceapplication/blob/main/distro/configuration/concepts/diagnosis_core-demo.csv

All concepts with the data class "Diagnosis" will automatically be visible in the diagnosis dropdown of the UI.

**Comment by Jexsie** [comment]
Hey @michaelbontyes, am taking this up if not one is assigned

**Comment by archnalan** [comment]
@Jexsie  how far with this claim... Any blockers?

**Comment by WodPachua** [comment]
Hello @Jexsie any updates on this?

**Comment by Jexsie** [comment]
Hey @WodPachua,  I think you can take over this issue. I lack the context to pursue it. The major blocker is recording new concepts using the concept dictionary more so when it comes to `concept mapping`. I will be glad to flow along with your fix
