### ISSUE TITLE
Add billable services in billing using Liquibase domain with Initializer

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#36]
Add the following Lab tests as billable services in OpenMRS Billing using Liquibase (SQL commands):
https://docs.google.com/spreadsheets/d/1ZyqsvdSMR5sJ5JOQN47TLaPucLZOtB5mofWwiooz42E/edit?gid=1036769692#gid=1036769692

Initializer documentation for Liquibase:
https://github.com/mekomsolutions/openmrs-module-initializer/blob/master/readme/liquibase.md

**Comment by WodPachua** [comment]
@michaelbontyes need some clarity with the price, are we using one payment mode, say cash/insurance only? Is the price we are using cost less insured cost?

**Comment by michaelbontyes** [comment]
@WodPachua , there are 2 prices for each billable service: **non-insured** and **insured**. Then upon billing at the cashier, patients can pay with **cash** and **mobile money**.

Billable services with their prices are ready to be imported in OpenMRS (probably using Liquibase migration scripts) for Lab Tests, Drugs, and Proced
<img width="2405" alt="Screenshot 2024-10-02 at 3 00 21 PM" src="https://github.com/user-attachments/assets/0a2364ae-1132-4bc0-bdc3-7851a7408c2d">
ures. For example:

**Comment by WodPachua** [comment]
I was looking at that specification doc actually, saw two prices, that's what kinda wasn't clear.

Correct me if am wrong, In otherwords our payment modes are 'insured' and 'non-insured'?

**Comment by WodPachua** [comment]
Maybe lemme create a draft PR and share, just to ensure I understand the requirement here

**Comment by michaelbontyes** [comment]
What if we create 4 payement methods for each billable service:
- Cash (insured)
- Cash (non-insured)
- Mobile money (insured)
- Mobile money (non-insured)

**Comment by michaelbontyes** [comment]
Ideally, it would be good to separate "**Prices**" (insured, non-insured) defined for each billable service, and "**Payement methods**" using when paying the bill at the cashier. Should we bring the question during the billing squad call or on billing Slack channel?

**Comment by WodPachua** [comment]
Sure, I think what is currently supported is for use cases where you have different prices for different payment methods... under each billable service, say TestA, costs 100.0 under cash, 200.0 under Mobile Money, 300.0 under Insurance...
