### ISSUE TITLE
Enable User Onboarding

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#40]
Enable the module and test tooltip scenarios as UVL EMR will be the first implementation to test it in action in October:
https://talk.openmrs.org/t/gsoc-2024-o3-user-onboarding-final-evaluation/43463/2?u=michaelbontyes

Explanation:
https://www.youtube.com/watch?v=ybd7hdtG89c

As an example, this is currently enable on RefApp:
https://github.com/openmrs/openmrs-distro-referenceapplication/blob/a085dc22659ed7e54bedb8cd3ed347a14f9b189d/frontend/spa-assemble-config.json#L39
And visible here:
<img width="1679" alt="Screenshot 2024-10-01 at 6 05 35 PM" src="https://github.com/user-attachments/assets/24a129bb-7009-47fc-ada5-f3cd939d7b54">

Configuration of scenarios are made possible in frontend configuration:
<img width="1100" alt="Screenshot 2024-10-01 at 6 07 06 PM" src="https://github.com/user-attachments/assets/1ae48024-1af9-471f-8806-46dd53423cf9">

Documentation contribution to explain how to configure and use it will also be needed. 

The module should be updated to allow translations of tutorials - which is needed for Burundi has existing tutorials coming out of the box with the module should be translated in French (can be done with ChatGPT, then French speaker will review).

**Comment by basrem** [comment]
Hi @michaelbontyes seems I don't have privileges to assign myself this ticket.Please assign this to me

**Comment by michaelbontyes** [comment]
@basrem , I informed [@Vijay](https://openmrs.slack.com/team/U06CTPD069J) about the need to add translation support for the tutorials themselves. Don't hesitate to communicate directly with him as needed.

**Comment by basrem** [comment]
Thanks @michaelbontyes, I definitely will
