### ISSUE TITLE
Create first report and visualization for children patients (Under 5 program)

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#46]
The need

- The clinic is looking for a **monthly report** of all the **patients with a visit/encounter** who's **age is less than 5 years old** 
- This allows to count the number of children under 5 years old who visited the clinic, month by month. 
- The fields required in the report are: **patient ID, patient date of birth, age, first name, last name**
- Use [OpenMRS reporting](https://guide.openmrs.org/using-data/reporting/#combining-cohort-queries) to build the report and [data visualizer ](https://github.com/METS-Programme/esm-ugandaemr-data-visualizer)module to render it in the frontend

**Comment by michaelbontyes** [comment]
Hello @dancinoman , is everything ok with the reporting?

**Comment by dancinoman** [comment]
Gitpod has decided to not collaborate today. I was about to diagnose what is not working on. 
I am experiencing difficulties with the queries because I am able to get child under 5 years old but when I want to have a report between startDate and endDate it returns all patient regardless of the visited dates.

**Comment by dancinoman** [comment]
Good news things are going great so far with queries. At the same time I would like to know if we should include also inactived patients?

**Comment by dancinoman** [comment]
Now a report is scheduled monthly as you can see here on the first day of the month.
![Image](https://github.com/user-attachments/assets/cd40d21e-7845-40bf-bf4f-87e8d4181c4a)

and that is the report of the children under 5 years old
![Image](https://github.com/user-attachments/assets/d3f34c7f-ac11-4132-a045-7b36bc3d01fb)

Im ready to meet Isaac how data visualiser works we are planning that meeting for this week.
