### ISSUE TITLE
Add lab results

### ISSUE THREAD

**Issue by Didifi87** [MadiroGlobalHealth/UVL-EMR#62]
It seems impossible to save Lab results, this is the message of error that occurs when i save the results.
![Lab results](https://github.com/user-attachments/assets/fdd7eaaa-d4a5-4041-a95f-a258acf8bfdf)

**Comment by michaelbontyes** [comment]
@Didifi87 can you try again? This message sometimes happen because of internet availability

**Comment by Didifi87** [comment]
Hello Michael, probably it was caused by internet because today i try again and it runs well. Thank you.

**Comment by michaelbontyes** [comment]
@Didifi87 can we then close this issue? Thank you
