### ISSUE TITLE
Not able to complete prescription

### ISSUE THREAD

**Issue by Didifi87** [MadiroGlobalHealth/UVL-EMR#63]
It seems impossible to do prescription, here are a capture of message that occurs
![prescription](https://github.com/user-attachments/assets/18c49d37-5a45-4430-b2c8-8b777fe57c7f)

**Comment by suubi-joshua** [comment]
@Didifi87 have you tried to prescribe other medications other than Quinine

**Comment by suubi-joshua** [comment]
@Didifi87 I have also realized that this error occurs if you use the CES unit but with other units quine can be prescribed ie choose another unit measurement .
