### ISSUE TITLE
Patient Age in Dispensing

### ISSUE THREAD

**Issue by Marian-Bernice** [MadiroGlobalHealth/UVL-EMR#65]
Proposal to show patient age in the dispensing app. Below is what we currently have:

![image](https://github.com/user-attachments/assets/d069d941-0fc5-4968-8a20-c461e8229cc2)

**Comment by suubi-joshua** [comment]
@Marian-Bernice there is some work going on this[ here]( https://github.com/openmrs/openmrs-esm-dispensing-app/pull/126)

**Comment by suubi-joshua** [comment]
@Marian-Bernice the PR for this work was merged in the latest release. SO all is good this can be closed.
