### ISSUE TITLE
UVL-1: Add "UVL" to Docker volumes and Containers

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#8]
When running UVL-EMR today, it uses the default naming from Ozone for volumes and containers. For examples:

Volumes:
![Image](https://github.com/user-attachments/assets/032630f5-5470-4570-9b35-f1e84b0ab6c1)
Containers
![Image](https://github.com/user-attachments/assets/d1d35774-e5e9-4e47-a725-6ae66767935c)

The objective of this ticket is to modify the Ozone build and Docker Compose files to add "**UVL**" to  volumes and containers to clearly identify them as part of the UVL project.

**Comment by michaelbontyes** [comment]
Hi @sherrif10, I tested the PR locally but it doesn't change the names.

**Comment by sherrif10** [comment]
Hello @michaelbontyes  @jnsereko  , Am kinda blocked  , however is there any example i can bench mark on

**Comment by michaelbontyes** [comment]
This ticket actually seems resolved:
<img width="313" alt="Screenshot 2024-10-02 at 3 38 39 PM" src="https://github.com/user-attachments/assets/8ecb2273-dafc-4922-9097-4605ee934375">
<img width="432" alt="Screenshot 2024-10-02 at 3 38 43 PM" src="https://github.com/user-attachments/assets/881b9448-c3c2-4d71-afca-85bb24670185">
