### ISSUE TITLE
Add service types in billing module

### ISSUE THREAD

**Issue by michaelbontyes** [MadiroGlobalHealth/UVL-EMR#9]
Add service types:

- Visit
- Procedure
- Drug
- Lab test

![Image](https://github.com/user-attachments/assets/9da89f68-8322-4bbb-900e-adfaa034fa18)

Services can be listed as answers in a coded concept with the UUID "21b8cf43-9f9f-4d02-9f4a-d710ece54261" using the Initialiser "Concept" domain. 

Example (not the right UUID though):

![Image](https://github.com/user-attachments/assets/f2c05b21-1d2a-4b13-991c-66654baaa23b)

**Comment by michaelbontyes** [comment]
Adding where the service types concept UUID is set in the UI:

![Image](https://github.com/user-attachments/assets/36969479-2211-4cf2-8abe-930725217c62)

**Comment by caitlinmac** [comment]
Note these already exist under the concept 'Services' 

![image](https://github.com/user-attachments/assets/13c785c5-c1af-4c9b-b2a4-286c93994083)

**Comment by caitlinmac** [comment]
Created new concept that references those same Set Members under Answer: 
![image](https://github.com/user-attachments/assets/e1e39545-9369-4816-88a2-96e8a77894b7)

**Comment by caitlinmac** [comment]
Working on fixing my local ui so that I can add this uuid into the json config and ensure the outcome works!

**Comment by caitlinmac** [comment]
fixed issues running ui on localhost - have updated local config file with concept uuid but not seeing changes in the ui on localhost
![Screenshot 2024-09-26 at 7 02 06 PM](https://github.com/user-attachments/assets/8acf66db-1022-41bd-bfb0-dc5d7bdc76b6)
